# Generated by Django 5.0.14 on 2026-08-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_organization'),
        ('tasks', '0004_remove_task_sub_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubProject',
        ),
    ]
