# Generated by Django 5.0.14 on 2026-08-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_subproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectMember',
        ),
    ]
