# Generated by Django 5.0.14 on 2026-08-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_client_name_project_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
