# Generated by Django 5.0.14 on 2026-09-05 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_invitation_role_alter_membership_role'),
        ('notifications', '0002_alter_notification_type'),
        ('projects', '0007_project_client'),
        ('tasks', '0012_remove_taskdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'recipient', 'is_read'], name='notificatio_organiz_5cc15d_idx'),
        ),
    ]
