# Generated by Django 5.0.14 on 2026-09-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UNASSIGNED', 'Task Unassigned'), ('TASK_REASSIGNED', 'Task Reassigned'), ('TASK_DUE_TODAY', 'Task Due Today'), ('TASK_DUE_SOON', 'Task Due Soon'), ('TASK_OVERDUE', 'Task Overdue'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_COMPLETED_LATE', 'Task Completed Late'), ('LATE_TASK_SUBMISSION', 'Late Task Submission'), ('TASK_REOPENED', 'Task Reopened'), ('TASK_PENDING_APPROVAL', 'Task Submitted for Approval'), ('TASK_APPROVED', 'Task Approved'), ('TASK_COMMENT_ADDED', 'Task Comment Added'), ('TASK_ATTACHMENT_ADDED', 'Task Attachment Added'), ('TASK_LINK_ADDED', 'Task Link Added'), ('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('MEMBER_ADDED', 'Member Added'), ('MEMBER_DEACTIVATED', 'Member Deactivated'), ('MEMBER_REACTIVATED', 'Member Reactivated'), ('SYSTEM', 'System')], max_length=50),
        ),
    ]
