# Generated by Django 5.0.14 on 2026-08-30 18:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_customuser_deactivated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeepItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('FOLDER', 'Folder'), ('DOCUMENT', 'Document'), ('NOTE', 'Note'), ('SPREADSHEET', 'Spreadsheet')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('document_content', models.TextField(blank=True, default='')),
                ('spreadsheet_data', models.JSONField(blank=True, default=dict)),
                ('original_import_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('original_import_format', models.CharField(blank=True, max_length=50, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('import_warnings', models.JSONField(blank=True, default=list)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_keep_items', to=settings.AUTH_USER_MODEL)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_keep_items', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keep_items', to='accounts.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_keep_items', to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='keep.keepitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_keep_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeepAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='keep.keepitem')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KeepPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('ONLY_ME', 'Only Me'), ('YOU_AND_ADMINS', 'You + Admins'), ('EVERYONE', 'Everyone'), ('SPECIFIC', 'Specific People')], default='ONLY_ME', max_length=20)),
                ('role', models.CharField(choices=[('VIEW', 'Can View'), ('EDIT', 'Can Edit')], default='VIEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='keep.keepitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keep_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeepRecentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_opened_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recents', to='keep.keepitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keep_recents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_opened_at'],
            },
        ),
        migrations.CreateModel(
            name='KeepShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('permission', models.CharField(choices=[('VIEW', 'Can View'), ('EDIT', 'Can Edit')], default='VIEW', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='keep.keepitem')),
            ],
        ),
        migrations.CreateModel(
            name='KeepUserPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pins', to='keep.keepitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keep_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeepVersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('content_snapshot', models.TextField(blank=True, default='')),
                ('spreadsheet_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='keep.keepitem')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='keepitem',
            index=models.Index(fields=['owner'], name='keep_keepit_owner_i_fb26dd_idx'),
        ),
        migrations.AddIndex(
            model_name='keepitem',
            index=models.Index(fields=['organization'], name='keep_keepit_organiz_67ed78_idx'),
        ),
        migrations.AddIndex(
            model_name='keepitem',
            index=models.Index(fields=['parent_folder'], name='keep_keepit_parent__2f1f51_idx'),
        ),
        migrations.AddIndex(
            model_name='keepitem',
            index=models.Index(fields=['item_type'], name='keep_keepit_item_ty_818440_idx'),
        ),
        migrations.AddIndex(
            model_name='keepitem',
            index=models.Index(fields=['is_deleted'], name='keep_keepit_is_dele_eb9aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='keepitem',
            index=models.Index(fields=['created_at'], name='keep_keepit_created_4d8bcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keeppermission',
            unique_together={('item', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='keeprecentitem',
            unique_together={('user', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='keepuserpin',
            unique_together={('user', 'item')},
        ),
    ]
