# Generated by Django 5.0.14 on 2026-09-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='keep_files/'),
        ),
        migrations.AddField(
            model_name='keepitem',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keepitem',
            name='file_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='keepitem',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='keepitem',
            name='item_type',
            field=models.CharField(choices=[('FOLDER', 'Folder'), ('DOCUMENT', 'Document'), ('NOTE', 'Note'), ('SPREADSHEET', 'Spreadsheet'), ('FILE', 'File')], max_length=20),
        ),
    ]
