# Generated by Django 5.0.14 on 2026-08-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enable_task_types',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='weekly_capacity_hours',
            field=models.IntegerField(default=40),
        ),
    ]
