# Generated by Django 5.0.14 on 2026-08-31 07:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def backfill_organizations_and_memberships(apps, schema_editor):
    Organization = apps.get_model('accounts', 'Organization')
    CustomUser = apps.get_model('accounts', 'CustomUser')
    Membership = apps.get_model('accounts', 'Membership')
    
    default_org = Organization.objects.filter(slug='zywo').first() or Organization.objects.first()
    if not default_org:
        default_org = Organization.objects.create(
            name='Zywo',
            slug='zywo',
            enable_task_types=True,
            weekly_capacity_hours=40
        )
    else:
        if default_org.name != 'Zywo' or default_org.slug != 'zywo':
            default_org.name = 'Zywo'
            default_org.slug = 'zywo'
            default_org.save()
    
    for org in Organization.objects.filter(slug__isnull=True):
        from django.utils.text import slugify
        base_slug = slugify(org.name) or 'org'
        slug = base_slug
        c = 1
        while Organization.objects.filter(slug=slug).exclude(id=org.id).exists():
            slug = f"{base_slug}-{c}"
            c += 1
        org.slug = slug
        org.save()

    primary_admin = CustomUser.objects.filter(role='ADMIN').order_by('created_at').first() or CustomUser.objects.filter(is_superuser=True).first()

    for user in CustomUser.objects.all():
        target_role = 'ORG_ADMIN' if user == primary_admin else ('ADMIN' if user.role == 'ADMIN' else 'MEMBER')
        membership = Membership.objects.filter(user=user, organization=default_org).first()
        if not membership:
            membership = Membership.objects.create(
                organization=default_org,
                user=user,
                role=target_role,
                is_active=True
            )
        else:
            if membership.role == 'MEMBER' and user.role == 'ADMIN':
                membership.role = target_role
                membership.save()
        
        if not user.active_organization:
            user.active_organization = membership.organization
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_enable_task_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('ORG_ADMIN', 'Organization Admin'), ('ADMIN', 'Admin/Manager'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('ORG_ADMIN', 'Organization Admin'), ('ADMIN', 'Admin/Manager'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'organization'], name='accounts_me_user_id_ca92ca_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'role'], name='accounts_me_organiz_91db9c_idx'),
        ),
        migrations.RunPython(backfill_organizations_and_memberships, reverse_code=migrations.RunPython.noop),
    ]
