# Generated by Django 5.0.14 on 2026-09-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organization_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('ORG_ADMIN', 'Organisation admin'), ('ADMIN', 'Admin/Manager'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('ORG_ADMIN', 'Organisation admin'), ('ADMIN', 'Admin/Manager'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
