# Generated by Django 5.0.14 on 2026-09-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organization_timezone_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enable_task_approval',
            field=models.BooleanField(default=True),
        ),
    ]
