# Generated by Django 5.0.14 on 2026-08-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignee',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
