# Generated by Django 5.0.14 on 2026-08-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskassignee_completed_taskassignee_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sub_project',
        ),
    ]
