# Generated by Django 5.0.14 on 2026-08-10 06:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_assignment_history(apps, schema_editor):
    TaskAssignee = apps.get_model('tasks', 'TaskAssignee')
    TaskAssignmentHistory = apps.get_model('tasks', 'TaskAssignmentHistory')
    for ta in TaskAssignee.objects.all():
        TaskAssignmentHistory.objects.get_or_create(
            task=ta.task,
            user=ta.user,
            unassigned_at=None,
            defaults={
                'assigned_at': ta.task.created_at,
                'completed': ta.completed,
                'completed_at': ta.completed_at
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_sub_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_histories', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignment_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assigned_at'],
                'indexes': [models.Index(fields=['task', 'user'], name='tasks_taska_task_id_85f579_idx'), models.Index(fields=['assigned_at'], name='tasks_taska_assigne_245d4b_idx'), models.Index(fields=['unassigned_at'], name='tasks_taska_unassig_6d49ac_idx')],
            },
        ),
        migrations.RunPython(populate_assignment_history, reverse_code=migrations.RunPython.noop),
    ]
