# Generated by Django 5.0.14 on 2026-08-12 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskassignmenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTaskAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignmenthistory',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_histories', to='tasks.subtask'),
        ),
        migrations.AlterField(
            model_name='taskassignmenthistory',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_histories', to='tasks.task'),
        ),
        migrations.AddIndex(
            model_name='taskassignmenthistory',
            index=models.Index(fields=['subtask', 'user'], name='tasks_taska_subtask_374bac_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskassignmenthistory',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('subtask__isnull', True), ('task__isnull', False)), models.Q(('subtask__isnull', False), ('task__isnull', True)), _connector='OR'), name='history_exactly_one_work_item'),
        ),
        migrations.AddField(
            model_name='subtaskassignee',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_relationships', to='tasks.subtask'),
        ),
        migrations.AddField(
            model_name='subtaskassignee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subtaskassignee',
            index=models.Index(fields=['subtask'], name='tasks_subta_subtask_21bfd7_idx'),
        ),
        migrations.AddIndex(
            model_name='subtaskassignee',
            index=models.Index(fields=['user'], name='tasks_subta_user_id_fc06c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subtaskassignee',
            unique_together={('subtask', 'user')},
        ),
    ]
