# Generated by Django 5.0.14 on 2026-09-02 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_task_dates(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    TaskDate = apps.get_model('tasks', 'TaskDate')
    for task in Task.objects.filter(due_date__isnull=False):
        TaskDate.objects.get_or_create(task=task, date=task.due_date)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_actual_duration_seconds_task_allocated_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_dates', to='tasks.task')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['task'], name='tasks_taskd_task_id_913707_idx'), models.Index(fields=['date'], name='tasks_taskd_date_b5205a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='taskdate',
            constraint=models.UniqueConstraint(fields=('task', 'date'), name='unique_task_date'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdate',
            unique_together={('task', 'date')},
        ),
        migrations.RunPython(backfill_task_dates, reverse_code=migrations.RunPython.noop),
    ]
