# Generated by Django 5.0.14 on 2026-09-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='attachment_type',
            field=models.CharField(choices=[('file', 'File'), ('link', 'Link')], default='file', max_length=20),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
