# Generated by Django 5.0.14 on 2026-09-13 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organization_timezone_profile_timezone'),
        ('projects', '0007_project_client'),
        ('tasks', '0014_taskattachment_attachment_type_taskattachment_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='occurrence_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_instance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecurringTaskSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='WEEK', max_length=10)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('month_day', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_type', models.CharField(choices=[('NEVER', 'Never'), ('ON', 'On Date'), ('AFTER', 'After Occurrences')], default='NEVER', max_length=10)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('occurrence_count', models.PositiveIntegerField(blank=True, null=True)),
                ('current_occurrence_number', models.PositiveIntegerField(default=1)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_recurring_series', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_task_series', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='tasks.recurringtaskseries'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['recurring_series'], name='tasks_task_recurri_5d7edd_idx'),
        ),
    ]
