# Generated by Django 5.0.14 on 2026-09-14 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_organization_enable_task_approval'),
        ('projects', '0007_project_client'),
        ('tasks', '0015_task_occurrence_index_task_recurrence_instance_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='approval_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending'), ('CHANGES_REQUESTED', 'Changes Requested'), ('APPROVED', 'Approved'), ('NOT_REQUIRED', 'Not Required')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['approval_status'], name='tasks_task_approva_c37216_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['approver'], name='tasks_task_approve_bc36f4_idx'),
        ),
    ]
