# Generated by Django 5.0.14 on 2026-09-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_task_approval_required_task_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='approval_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('NOT_REQUIRED', 'Not Required')], default='NOT_STARTED', max_length=20),
        ),
    ]
