# Generated by Django 5.0.14 on 2026-08-08 23:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_REOPENED', 'Task Reopened'), ('SUBTASK_CREATED', 'Subtask Created'), ('SUBTASK_COMPLETED', 'Subtask Completed'), ('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_DELETED', 'Project Deleted'), ('SUBPROJECT_CREATED', 'Subproject Created'), ('PROFILE_UPDATED', 'Profile Updated')], max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='activity_ac_created_a8727e_idx'), models.Index(fields=['user'], name='activity_ac_user_id_f996d2_idx')],
            },
        ),
    ]
