# Generated by Django 5.0.14 on 2026-08-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='entity_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
